services:
  - type: web
    name: stephs-teacher-site
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: stephs-teacher-db
          property: connectionString

databases:
  - name: stephs-teacher-db
    plan: free
